export const CURRENCIES = [
  { code: 'USD', name: 'US Dollar',          symbol: '$',    rate: 1 },
  { code: 'EUR', name: 'Euro',               symbol: '€',    rate: 0.8629 },
  { code: 'GBP', name: 'British Pound',      symbol: '£',    rate: 0.7496 },
  { code: 'JPY', name: 'Japanese Yen',       symbol: '¥',    rate: 159.24 },
  { code: 'INR', name: 'Indian Rupee',       symbol: '₹',    rate: 93.77 },
  { code: 'IDR', name: 'Indonesian Rupiah',  symbol: 'Rp',   rate: 16977 },
  { code: 'PHP', name: 'Philippine Peso',    symbol: '₱',    rate: 59.91 },
  { code: 'CNY', name: 'Chinese Yuan',       symbol: '¥',    rate: 6.8863 },
  { code: 'KRW', name: 'South Korean Won',   symbol: '₩',    rate: 1498.88 },
  { code: 'AUD', name: 'Australian Dollar',  symbol: 'A$',   rate: 1.421 },
  { code: 'CAD', name: 'Canadian Dollar',    symbol: 'C$',   rate: 1.3722 },
  { code: 'CHF', name: 'Swiss Franc',        symbol: 'Fr',   rate: 0.788 },
  { code: 'HKD', name: 'Hong Kong Dollar',   symbol: 'HK$',  rate: 7.827 },
  { code: 'SGD', name: 'Singapore Dollar',   symbol: 'S$',   rate: 1.2822 },
  { code: 'MYR', name: 'Malaysian Ringgit',  symbol: 'RM',   rate: 3.9344 },
  { code: 'THB', name: 'Thai Baht',          symbol: '฿',    rate: 32.76 },
  { code: 'VND', name: 'Vietnamese Dong',    symbol: '₫',    rate: 26270 },
  { code: 'BDT', name: 'Bangladeshi Taka',   symbol: '৳',    rate: 122.82 },
  { code: 'PKR', name: 'Pakistani Rupee',    symbol: 'Rs',   rate: 279.19 },
  { code: 'LKR', name: 'Sri Lankan Rupee',   symbol: 'Rs',   rate: 310.97 },
  { code: 'AED', name: 'UAE Dirham',         symbol: 'AED',  rate: 3.6725 },
  { code: 'SAR', name: 'Saudi Riyal',        symbol: 'SAR',  rate: 3.75 },
  { code: 'QAR', name: 'Qatari Riyal',       symbol: 'QR',   rate: 3.64 },
  { code: 'KWD', name: 'Kuwaiti Dinar',      symbol: 'KD',   rate: 0.3065 },
  { code: 'BHD', name: 'Bahraini Dinar',     symbol: 'BD',   rate: 0.376 },
  { code: 'EGP', name: 'Egyptian Pound',     symbol: 'E£',   rate: 52.32 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R',    rate: 17.0 },
  { code: 'NGN', name: 'Nigerian Naira',     symbol: '₦',    rate: 1356 },
  { code: 'KES', name: 'Kenyan Shilling',    symbol: 'KSh',  rate: 129.6 },
  { code: 'MXN', name: 'Mexican Peso',       symbol: 'MX$',  rate: 17.9 },
  { code: 'BRL', name: 'Brazilian Real',     symbol: 'R$',   rate: 5.3015 },
  { code: 'ARS', name: 'Argentine Peso',     symbol: 'AR$',  rate: 1391 },
  { code: 'CLP', name: 'Chilean Peso',       symbol: 'CL$',  rate: 927.18 },
  { code: 'COP', name: 'Colombian Peso',     symbol: 'CO$',  rate: 3699 },
  { code: 'PEN', name: 'Peruvian Sol',       symbol: 'S/',   rate: 3.4777 },
  { code: 'TRY', name: 'Turkish Lira',       symbol: '₺',    rate: 44.29 },
  { code: 'RUB', name: 'Russian Ruble',      symbol: '₽',    rate: 83.6 },
  { code: 'PLN', name: 'Polish Zloty',       symbol: 'zł',   rate: 3.6943 },
  { code: 'CZK', name: 'Czech Koruna',       symbol: 'Kč',   rate: 21.15 },
  { code: 'HUF', name: 'Hungarian Forint',   symbol: 'Ft',   rate: 339.65 },
  { code: 'SEK', name: 'Swedish Krona',      symbol: 'kr',   rate: 9.341 },
  { code: 'NOK', name: 'Norwegian Krone',    symbol: 'kr',   rate: 9.5648 },
  { code: 'DKK', name: 'Danish Krone',       symbol: 'kr',   rate: 6.4587 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$',  rate: 1.7127 },
  { code: 'ILS', name: 'Israeli Shekel',     symbol: '₪',    rate: 3.1109 },
  { code: 'TWD', name: 'Taiwan Dollar',      symbol: 'NT$',  rate: 32.05 },
  { code: 'MNT', name: 'Mongolian Tugrik',   symbol: '₮',    rate: 3571 },
  { code: 'MAD', name: 'Moroccan Dirham',    symbol: 'MAD',  rate: 9.3548 },
  { code: 'DZD', name: 'Algerian Dinar',     symbol: 'DA',   rate: 132.37 },
  { code: 'NPR', name: 'Nepalese Rupee',     symbol: 'Rs',   rate: 150.03 },
];

export const getCurrencyByCode = (code) =>
  CURRENCIES.find((c) => c.code === code) || CURRENCIES[0];
