export const CURRENCIES = [
  { code: 'USD', name: 'US Dollar',          symbol: '$',    rate: 1 },
  { code: 'EUR', name: 'Euro',               symbol: '\u20ac',    rate: 0.92 },
  { code: 'GBP', name: 'British Pound',      symbol: '\u00a3',    rate: 0.79 },
  { code: 'JPY', name: 'Japanese Yen',       symbol: '\u00a5',   rate: 149.50 },
  { code: 'INR', name: 'Indian Rupee',       symbol: '\u20b9',    rate: 83.12 },
  { code: 'IDR', name: 'Indonesian Rupiah',  symbol: 'Rp',   rate: 15650 },
  { code: 'PHP', name: 'Philippine Peso',    symbol: '\u20b1',    rate: 56.50 },
  { code: 'CNY', name: 'Chinese Yuan',       symbol: '\u00a5',    rate: 7.24 },
  { code: 'KRW', name: 'South Korean Won',   symbol: '\u20a9',   rate: 1325 },
  { code: 'AUD', name: 'Australian Dollar',  symbol: 'A$',   rate: 1.53 },
  { code: 'CAD', name: 'Canadian Dollar',    symbol: 'C$',   rate: 1.36 },
  { code: 'CHF', name: 'Swiss Franc',        symbol: 'Fr',   rate: 0.89 },
  { code: 'HKD', name: 'Hong Kong Dollar',   symbol: 'HK$',  rate: 7.82 },
  { code: 'SGD', name: 'Singapore Dollar',   symbol: 'S$',   rate: 1.34 },
  { code: 'MYR', name: 'Malaysian Ringgit',  symbol: 'RM',   rate: 4.72 },
  { code: 'THB', name: 'Thai Baht',          symbol: '\u0e3f',    rate: 35.10 },
  { code: 'VND', name: 'Vietnamese Dong',    symbol: '\u20ab',    rate: 24380 },
  { code: 'BDT', name: 'Bangladeshi Taka',   symbol: '\u09f3',    rate: 110.40 },
  { code: 'PKR', name: 'Pakistani Rupee',    symbol: 'Rs',   rate: 278.50 },
  { code: 'LKR', name: 'Sri Lankan Rupee',   symbol: 'Rs',   rate: 321.50 },
  { code: 'AED', name: 'UAE Dirham',         symbol: 'AED',  rate: 3.67 },
  { code: 'SAR', name: 'Saudi Riyal',        symbol: 'SAR',  rate: 3.75 },
  { code: 'QAR', name: 'Qatari Riyal',       symbol: 'QR',   rate: 3.64 },
  { code: 'KWD', name: 'Kuwaiti Dinar',      symbol: 'KD',   rate: 0.308 },
  { code: 'BHD', name: 'Bahraini Dinar',     symbol: 'BD',   rate: 0.376 },
  { code: 'EGP', name: 'Egyptian Pound',     symbol: 'E\u00a3',   rate: 30.90 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R',    rate: 18.63 },
  { code: 'NGN', name: 'Nigerian Naira',     symbol: '\u20a6',    rate: 1475 },
  { code: 'KES', name: 'Kenyan Shilling',    symbol: 'KSh',  rate: 130.50 },
  { code: 'MXN', name: 'Mexican Peso',       symbol: 'MX$',  rate: 17.15 },
  { code: 'BRL', name: 'Brazilian Real',     symbol: 'R$',   rate: 4.97 },
  { code: 'ARS', name: 'Argentine Peso',     symbol: 'AR$',  rate: 820 },
  { code: 'CLP', name: 'Chilean Peso',       symbol: 'CL$',  rate: 895 },
  { code: 'COP', name: 'Colombian Peso',     symbol: 'CO$',  rate: 3950 },
  { code: 'PEN', name: 'Peruvian Sol',       symbol: 'S/',   rate: 3.72 },
  { code: 'TRY', name: 'Turkish Lira',       symbol: '\u20ba',    rate: 30.85 },
  { code: 'RUB', name: 'Russian Ruble',      symbol: '\u20bd',    rate: 91.50 },
  { code: 'PLN', name: 'Polish Zloty',       symbol: 'z\u0142',   rate: 3.99 },
  { code: 'CZK', name: 'Czech Koruna',       symbol: 'K\u010d',   rate: 22.85 },
  { code: 'HUF', name: 'Hungarian Forint',   symbol: 'Ft',   rate: 354 },
  { code: 'SEK', name: 'Swedish Krona',      symbol: 'kr',   rate: 10.42 },
  { code: 'NOK', name: 'Norwegian Krone',    symbol: 'kr',   rate: 10.58 },
  { code: 'DKK', name: 'Danish Krone',       symbol: 'kr',   rate: 6.89 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$',  rate: 1.63 },
  { code: 'ILS', name: 'Israeli Shekel',     symbol: '\u20aa',    rate: 3.71 },
  { code: 'TWD', name: 'Taiwan Dollar',      symbol: 'NT$',  rate: 31.65 },
  { code: 'MNT', name: 'Mongolian Tugrik',   symbol: '\u20ae',    rate: 3430 },
  { code: 'MAD', name: 'Moroccan Dirham',    symbol: 'MAD',  rate: 10.05 },
  { code: 'DZD', name: 'Algerian Dinar',     symbol: 'DA',   rate: 134.50 },
  { code: 'NPR', name: 'Nepalese Rupee',     symbol: 'Rs',   rate: 132.90 },
];

export const getCurrencyByCode = (code) =>
  CURRENCIES.find((c) => c.code === code) || CURRENCIES[0];
